### ISSUE TITLE
Argo CD behind reverse proxy

### ISSUE THREAD

**Issue by sambo2021** [arthurk/argocd-example-install#4]
it is not an issue, just want to add here if you using argo-cd behind reverse proxy, for example istio gateway and virtual service and adding sub path in virtual service for example '/argocd'
so u need to add those params in values.yaml

```
argo-cd:
  configs:
    params:
      server.insecure: true
      server.basehref: '/argocd'
      server.rootpath: '/argocd' 
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false

```
